name: build

on:
  workflow_dispatch:
  push:
   branches:
     - '**'
   paths:
     - '**.py'

# this does nothing as expected
defaults:
  run:
    working-directory: ./server

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'server/vrc-patpatpat.spec'
          requirements: 'server/requirements.txt'
          upload_exe_with_name: 'vrc-patpatpat'
      - uses: actions/upload-artifact@v4
        with:
          name: xref-vrc-patpatpat.html
          path: ./build/vrc-patpatpat/xref-vrc-patpatpat.html
  build-windows-debug:
    runs-on: windows-latest
    steps:
      - name: Create Executable with debug enabled
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'server/vrc-patpatpat-debug.spec'
          requirements: 'server/requirements.txt'
          upload_exe_with_name: 'vrc-patpatpat-debug'
      - uses: actions/upload-artifact@v4
        with:
          name: xref-vrc-patpatpat-debug.html
          path: ./build/vrc-patpatpat-debug/xref-vrc-patpatpat-debug.html